### PR TITLE
v1.0.0 Release

### PR DESCRIPTION
**Pull request by dancannon**
This update is not yet ready for release but I would appreciate any feedback regarding any of the changes in this PR or any other issues you might have with the driver as I hope this will be the last time I make any changes to the API for some time.

I will update the changelog with the full list of changes but here is a summary:
- RethinkDB 2.0 support
- Cluster/host discovery (ability to connect to multiple nodes in a cluster)
- Changed format for `Connect`
- Channel iterator helper
- Various small bug fixes

### CODE REVIEW

**Comment by ghost** [comment]
@dancannon So, this is the last time when it's possible to break the API and lint the code renaming all those exported methods and types: `DB`, `DBCreate`, `DBDrop`, `DBList`, `RQLDriverError`, `RQLClientError`, `RQLRuntimeError`, `RQLCompileError`, `RQLConnectionError`, etc. Or do you think it's too late to rename them?

**Comment by dancannon** [comment]
@anonx I am debating have one last release to try and fix any bugs with the new host discovery feature but yes this is the time to make any changes to those functions.

Are there any changes you would like to see?

**Comment by kofalt** [comment]
I'll try to have a look at these changes later this week, but it might end up getting pushed to the weekend :)

**Comment by dancannon** [comment]
Thanks @kofalt, no rush. I think I might release RC1 instead over the next couple of days to get some feedback and then release 1.0 once I am happy that #105 has not caused any issues.

**Comment by dancannon** [comment]
Closing this PR in favour of #168 as I don't think the driver is quite ready for v1.

**Comment by ghost** [comment]
> Are there any changes you would like to see?

@dancannon As I said, here is a list of methods, structs, and variables:
`Db`, `DbCreate`, `DbDrop`, `DbList`, `RqlDriverError`, `RqlClientError`, `RqlRuntimeError`, `RqlCompileError`, `RqlConnectionError`, and so forth.

After linting the code they should look as follows:
`DB`, `DBCreate`, `DBDrop`, `DBList`, `RQLDriverError`, `RQLClientError`, `RQLRuntimeError`, `RQLCompileError`, `RQLConnectionError`.

Here is a related link: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Comment by dancannon** [comment]
Ah right I see what you mean, apologies that I did not read your message properly. 

I think that I will not make any changes to the naming of these functions since this is same format as the JS driver and I try to keep this driver as similar as possible to the official drivers.

**Comment by ghost** [comment]
@dancannon In every language they use conventional way for that specific language.

**JavaScript** (http://rethinkdb.com/api/javascript/#db_create)

``` js
// Their JS version looks like Golang's conventional naming BTW.
r.dbCreate('superheroes').run(conn, callback)
```

**Python** (http://rethinkdb.com/api/python/#db_create)

``` python
r.db_create('superheroes').run(conn)
```

**Ruby** (http://rethinkdb.com/api/ruby/#db_create)

``` ruby
r.db_create('superheroes').run(conn)
```

**Comment by dancannon** [comment]
True, I'll consider making the change in the next major version.

**Pull request closed without merging**
