### PR TITLE
Session.IsConnected: use RLock instead of Lock to improve performance

### PR DESCRIPTION
**Pull request by ekle**
single inserts go up from ~100 to more than 4000 on my dualcore system.
(100 goroutines concurrently inserting single values in local rethinkdb)

### CODE REVIEW

**Comment by dancannon** [comment]
Thanks!

**Comment by iKonrad** [comment]
@dancannon Hi, when do you plan to get that deployed? It indeed dramatically improves performance.

Also, @ekle would you mind posting a code snippet that you used for testing that got you 4k writes per second? I've done few tests with for loop -> goroutine and it usually crashes at around 1.5k/sec with error "too many files opened". And I'm closing the cursors with cursor.Close()

Would that be my machine that can't handle anything beyond that or there's something with the code?

**Comment by ekle** [comment]
@iKonrad "too many files opened" likely means you are opening too many connections to the rethinkdb-server. 100 should be enough `ConnectOpts.MaxOpen = 100`.

i only get 4k with very simple writes, as i wanted to test the lib and not the speed of the server. (not tested with a big cluster) 
this is the code i used for testing: https://gist.github.com/ekle/1c99782159596d746c191589b2ea10c6
i looked up the writes/s in the rethinkdb webinterface.

**Comment by iKonrad** [comment]
Thanks! it make sense now.

I had MaxOpen set to 30, but opened the session 4000 times:
https://gist.github.com/iKonrad/2750bd1fd8f5a1bf527090ebba0ca376

So if I set MaxOpen to 100, that means one user can have up to 100 connections? 
So if 100 users used my app, the number of connections would be 100 * 100 = 10000?

**Comment by ekle** [comment]
this 100 is normally per instance of your service. 
creating a new connection-pool per user is usually not a good idea. 
the instance should share the pool for all users.

**Comment by iKonrad** [comment]
Ah gotcha. I think I got it now! Thanks

**Comment by dancannon** [comment]
Apologies for the delay, this has now been merged to master.

**Comment by ekle** [comment]
have you pushed the master ? currently it is not in: https://github.com/GoRethink/gorethink/blob/master/session.go#L173

**Comment by dancannon** [comment]
🙈  Sorry about that! Pushed the correct changes now.

**Pull request merged**
