### PR TITLE
Added json tags to ConnectOpts to make it serializable

### PR DESCRIPTION
**Pull request by or-else**
Added `json:"whatever,omitempty"` tags to ConnectOpts fields to make it (de-)serializable to/from json.

### CODE REVIEW

**Comment by CMogilko** [comment]
Could you please fix 2 tests in `encoding` pkg on occasion? It seems that in go master version using `%q` for compound types causes compiler error now instead of erroneous output.
It makes all checks green.

**Comment by or-else** [comment]
The test failure is weird. I don't understand why it fails just in these two cases and not in another dozen or so. There are lots of places where %q is used with types like `SliceStruct` and `Compound`. What's so special about `UnmarshalerPointer` and `outerType`?

**Comment by CMogilko** [comment]
I think that it is about passing `struct`s to `%q`. In go1.11 and lower it got erroneous output like `%!q(*struct {}=<nil>)` but in go master (and maybe in 1.12) it is compiler error now.
I don't know why dancannon used `%q` everywhere. But I suggest, the best solution is to implement `fmt.Stringer` interface with these types. Other option is to change modifier to `%v` or something, but if test fails it can print pointer instead of value.

**Comment by or-else** [comment]
Given that these are temporary structs, something like %+v should do the job. Implementing Stringer just to print test output seems like an overkill.

**Comment by or-else** [comment]
A correction: the `UnmarshalerPointer ` is global type and maybe should get a Stringer. The other type is temporary.

**Comment by or-else** [comment]
All green.

**Pull request merged**
