### PR TITLE
Bump Go versions in Travis CI.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Review by kirillDanshin — APPROVED** [review]
LGTM.
@dancannon merge it please

**Comment by AlekSi** [comment]
We can bump it to `1.7.5` now. :)

**Comment by kirillDanshin** [comment]
@AlekSi even more: we can wait 1.8 release and bump then :)

**Comment by dancannon** [comment]
Thanks @AlekSi + @kirillDanshin! Lets merge this now and we can update again when 1.8 has been released.

**Pull request merged**
