### PR TITLE
Blocking mocks for responses

### PR DESCRIPTION
**Pull request by CMogilko**
I refactored interfaces a bit #460 .
@arnodel take a look

### CODE REVIEW

**Review by arnodel — APPROVED** [review]
This looks great!  When looking at the code for #460 I didn't look as far as the `Connection` type, but now that I have it seems the correct approach to mock its `net.Conn` field.  Also the interface presented to the user of the mock object is improved.  Thanks @CMogilko for taking the time to do this.

One remark though: it might be better always to create a mock connection in `MockQuery.Return`.  For the "regular" arguments there would be a new case in the switch statement in `newMockConnection` that would create the appropriate `valueGetter`.  There would be two advantages to this:
- the code would be a bit simpler (less branching)
- the `MockQuery.Return` method would need to do less fiddling with the internals of the `Cursor` it creates.

**Comment by CMogilko** [comment]
done, @arnodel pls check if all your tests are ok with this new mocking.

**Comment by arnodel** [comment]
> done, @arnodel pls check if all your tests are ok with this new mocking.

Works well for me - I had to make some minor changes to some tests because of the new json marshalling / unmarshalling that occurs in mockConn.Read .  In my opinion this is an improvement, however could this break some currently successful tests?

**Comment by CMogilko** [comment]
@arnodel what kind of minor changes did you make?
ps. I found one mistake in encoding. fixed.

**Review by zeslava — APPROVED** [review]

**Comment by arnodel** [comment]
> @arnodel what kind of minor changes did you make?

Previously, the values in the mock response were put in the cursor buffer unchanged (see https://github.com/rethinkdb/rethinkdb-go/blob/master/mock.go#L340).  Now they are marshalled to json and unmarshalled in mockConn.Read, which will make them change (e.g. an integer will turn into a float64)

**Comment by CMogilko** [comment]
I think in some rare cases it can break compatibility. So it requires to increment major version however it is not so important change. Is it okay for you @arnodel to wait for other changes to justify major increment?

**Pull request merged**
